CONNECT SYS AS SYSDBA
CREATE SPFILE FROM PFILE = 'inits191954.ora';
STARTUP NOMOUNT;
CREATE DATABASE loudoven
	CHARACTER SET UTF8
	NATIONAL CHARACTER SET UTF8
	DATAFILE '/u01/bcu71/loudoven/node02/enofe98.dbf' 
		SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
	SYSAUX 
		DATAFILE '/u01/bcu71/loudoven/node03/gew78.dbf' 
		SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
	UNDO TABLESPACE undotbs1 
		DATAFILE '/u01/bcu71/loudoven/undo.dbf' 
		SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED
	DEFAULT TABLESPACE users 
		DATAFILE '/u01/bcu71/loudoven/node01/ixayuyu664.dbf' 
		SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;

	CREATE TABLESPACE NICE_ORANGE_BIRD datafile 
		'/u01/bcu71/loudoven/node03/niceorangebird01.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED, 
		'/u01/bcu71/loudoven/node03/niceorangebird02.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED, 
		'/u01/bcu71/loudoven/node01/niceorangebird03.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
	CREATE TABLESPACE NICE_ORANGE_MEAT datafile 
		'/u01/bcu71/loudoven/node03/niceorangemeat01.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED, 
		'/u01/bcu71/loudoven/node03/niceorangemeat02.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED, 
		'/u01/bcu71/loudoven/node03/niceorangemeat03.dbf' SIZE 100M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED;
	@?/rdbms/admin/catalog.sql
	@?/rdbms/admin/catproc.sql
EXIT
