# libreport 0.2 by Ivan Chebykin <ivan@chebykin.org>

LOCAL_HEADERS=$(wildcard *.def)
LOCAL_TEMPLATES=$(wildcard *.tex)
LOCAL_METADATA=$(wildcard *.yaml)
LOCAL_FLAGS=--bibliography bib.bib --csl gost-r-7-0-5-2008-numeric.csl \
			--top-level-division=chapter -N

INCLUDE_DIR=../../../libreport

include $(INCLUDE_DIR)/Makefile
