# libreport 0.2 by Ivan Chebykin <ivan@chebykin.org>

LOCAL_HEADERS=$(wildcard *.def)
LOCAL_TEMPLATES=$(wildcard *.tex)
LOCAL_METADATA=$(wildcard *.yaml)
LOCAL_FLAGS=

INCLUDE_DIR=../../../libreport

include $(INCLUDE_DIR)/Makefile
