
package lab1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonWebService", targetNamespace = "http://lab1.webservices.chebykin.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonWebService {


    /**
     * 
     * @param fieldsAndValues
     * @return
     *     returns java.util.List<lab1.Person>
     * @throws InvalidFilterException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersons", targetNamespace = "http://lab1.webservices.chebykin.org/", className = "lab1.GetPersons")
    @ResponseWrapper(localName = "getPersonsResponse", targetNamespace = "http://lab1.webservices.chebykin.org/", className = "lab1.GetPersonsResponse")
    public List<Person> getPersons(
        @WebParam(name = "fieldsAndValues", targetNamespace = "")
        PersonFilter fieldsAndValues)
        throws InvalidFilterException
    ;

}
